[package]
name = "piece_of_pi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bigdecimal = "*"
num-bigint = "*"
num-bigfloat = "*"
num-traits = "*"
num-rational = "*"
